[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.mypy]
mypy_path = "src"
ignore_missing_imports = true
follow_imports = "skip"
strict_optional = false
disallow_untyped_defs = false
check_untyped_defs = false


[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["chokkhu"]
src_paths = ["src"]


[tool.black]
line-length = 88

