"""Chokkhu: Pure NumPy and SciPy Enterprise AI and Machine Learning Library."""

from __future__ import annotations

import importlib
from typing import Any, List

__version__ = "1.6.0"
__author__ = "Chokkhu Team"

_ALIASES: dict[str, list[str]] = {
    "Ridge": [".models.ml.glm", "RidgeRegression"],
    "Lasso": [".models.ml.glm", "LassoRegression"],
    "ElasticNet": [".models.ml.glm", "ElasticNet"],
    "RandomForestClassifier": [".models.ml.random_forest", "RandomForest"],
    "RandomForestRegressor": [".models.ml.random_forest", "RandomForest"],
    "DecisionTreeClassifier": [".models.ml.decision_tree", "DecisionTree"],
    "DecisionTreeRegressor": [".models.ml.decision_tree", "DecisionTree"],
    "KNeighborsClassifier": [".models.ml.knn_spatial", "KNNClassifier"],
    "KNeighborsRegressor": [".models.ml.knn_spatial", "KNNRegressor"],
    "Pipeline": [".pipeline.engine", "ChokkhuPipeline"],
    "pipeline": [".pipeline.engine", "pipeline"],
}

_LAZY_IMPORTS: dict[str, str] = {
    "annotations": ".eda.tabular.plotters",
    "GaussianProcessSurrogate": ".automl",
    "expected_improvement": ".automl",
    "upper_confidence_bound": ".automl",
    "BayesianOptimization": ".automl",
    "Hyperband": ".automl",
    "BOHB": ".automl",
    "SuperLearner": ".pipeline",
    "StackingEnsemble": ".automl",
    "DARTS": ".automl",
    "GeneticPipelineSearch": ".automl",
    "PipelineIndividual": ".automl",
    "DynamicEnsembleSelection": ".automl",
    "AutoTrainer": ".automl",
    "AutoMLResult": ".automl",
    "auto_train": ".automl",
    "Logger": ".utils",
    "fix_dtypes": ".cleaning",
    "remove_duplicates": ".cleaning",
    "handle_missing": ".cleaning",
    "handle_outliers": ".cleaning",
    "EllipticEnvelope": ".cleaning",
    "LocalOutlierFactor": ".cleaning",
    "clean": ".cleaning",
    "SpectralGraphClusterer": ".clustering",
    "UniformQuantizer": ".compression",
    "PostTrainingQuantizer": ".compression",
    "QuantizedLinear": ".compression",
    "MagnitudePruner": ".compression",
    "GlobalMagnitudePruner": ".compression",
    "KnowledgeDistiller": ".compression",
    "FeatureDistiller": ".compression",
    "EWC": ".continual",
    "ElasticWeightConsolidation": ".continual",
    "DERPlusPlus": ".continual",
    "DarkExperienceReplay": ".continual",
    "DataShapleyValuation": ".data",
    "FacilityLocationCoresetSelector": ".data",
    "ImageEDA": ".eda.image",
    "tabular": ".eda.tabular",
    "image": ".eda",
    "EvaluationResult": ".evaluation",
    "evaluate": ".evaluation",
    "accuracy_score": ".evaluation",
    "f1_score": ".evaluation",
    "precision_score": ".evaluation",
    "recall_score": ".evaluation",
    "confusion_matrix": ".evaluation",
    "log_loss": ".evaluation",
    "mean_absolute_error": ".evaluation",
    "mean_squared_error": ".evaluation",
    "pr_auc_score": ".evaluation",
    "precision_recall_f1": ".evaluation",
    "r2_score": ".evaluation",
    "roc_auc_score": ".evaluation",
    "root_mean_squared_error": ".evaluation",
    "MaximumMeanDiscrepancyTest": ".evaluation",
    "PopulationStabilityIndex": ".evaluation",
    "WachterCounterfactualExplainer": ".explainability",
    "ActivationPatchingEngine": ".explainability",
    "ExplanationResult": ".explainability",
    "explain": ".explainability",
    "permutation_feature_importance": ".explainability",
    "AttentionRollout": ".explainability",
    "DirectLogitAttribution": ".explainability",
    "TopKSAE": ".explainability",
    "JumpReLU": ".explainability",
    "ActivationPatching": ".explainability",
    "DeepLIFT": ".explainability",
    "IntegratedGradients": ".explainability",
    "SmoothGrad": ".explainability",
    "partial_dependence": ".explainability",
    "kernel_shap": ".explainability",
    "TCAV": ".explainability",
    "demographic_parity_difference": ".fairness",
    "demographic_parity_ratio": ".fairness",
    "equal_opportunity_difference": ".fairness",
    "equalized_odds_difference": ".fairness",
    "disparate_impact_ratio": ".fairness",
    "theil_index": ".fairness",
    "fairness_report": ".fairness",
    "ReweighingTransformer": ".fairness",
    "DisparateImpactRemover": ".fairness",
    "ThresholdOptimizer": ".fairness",
    "PoincareBallEmbedding": ".geometry",
    "LorentzManifold": ".geometry",
    "CellularSheaf": ".geometry",
    "SheafDiffusionLayer": ".geometry",
    "SheafNeuralNetwork": ".geometry",
    "GeographicallyWeightedRegression": ".geospatial",
    "OrdinaryKriging": ".geospatial",
    "SpatialAutoregression": ".geospatial",
    "SpatialWeights": ".geospatial",
    "local_morans_i": ".geospatial",
    "morans_i": ".geospatial",
    "HyperdimensionalVector": ".hdc",
    "HDCClassifier": ".hdc",
    "KraskovMutualInformation": ".information",
    "MultivariateKDE": ".information",
    "DeepVariationalInformationBottleneck": ".information",
    "save": ".io",
    "load": ".io",
    "load_safetensors": ".io",
    "save_safetensors": ".io",
    "TIESMerging": ".models.merging",
    "DARE": ".models.merging",
    "SLERP": ".models.merging",
    "RegMean": ".models.merging",
    "FrankWolfeEnsemble": ".models.merging",
    "SphericalHarmonics": ".models.geometric",
    "SE3EquivariantConv": ".models.geometric",
    "EnergyBasedModel": ".models.energy",
    "SlicedScoreMatching": ".models.energy",
    "ScoreMatchingEBM": ".models.energy",
    "AnnealedLangevinDynamics": ".models.energy",
    "M5ModelTree": ".models.trees",
    "RuleFitRegressor": ".models.trees",
    "RuleFitClassifier": ".models.trees",
    "MAML": ".models.meta",
    "MAPElites": ".models.meta",
    "LIFNeuron": ".models.dl",
    "SpikingNeuralNetwork": ".models.dl",
    "DeepEquilibriumModel": ".models.dl",
    "DynamicModeDecomposition": ".models.sciml",
    "ExtendedDMD": ".models.sciml",
    "AdaBoostClassifier": ".models.ml",
    "AdaBoostRegressor": ".models.ml",
    "ExtraTreesClassifier": ".models.ml",
    "ExtraTreesRegressor": ".models.ml",
    "KMedoids": ".models.ml",
    "OPTICS": ".models.ml",
    "IsolationForest": ".models.trees",
    "HistGradientBoostingClassifier": ".models.ml",
    "HistGradientBoostingRegressor": ".models.ml",
    "SVC": ".models.ml",
    "SVR": ".models.ml",
    "OneClassSVM": ".models.ml",
    "LinearSVC": ".models.ml",
    "NearestCentroid": ".models.ml",
    "RadiusNeighborsClassifier": ".models.ml",
    "RadiusNeighborsRegressor": ".models.ml",
    "RidgeRegression": ".models.ml",
    "LassoRegression": ".models.ml",
    "ElasticNet": ".models.ml",
    "HuberRegressor": ".models.ml",
    "BayesianRidge": ".models.ml",
    "ARDRegression": ".models.ml",
    "PassiveAggressiveClassifier": ".models.ml",
    "PassiveAggressiveRegressor": ".models.ml",
    "GaussianNB": ".models.ml",
    "MultinomialNB": ".models.ml",
    "BernoulliNB": ".models.ml",
    "ComplementNB": ".models.ml",
    "LinearDiscriminantAnalysis": ".models.ml",
    "QuadraticDiscriminantAnalysis": ".models.ml",
    "LDAClassifier": ".models.ml",
    "QDAClassifier": ".models.ml",
    "MiniBatchKMeans": ".models.ml",
    "GaussianMixture": ".models.ml",
    "SpectralClustering": ".models.ml",
    "KNNClassifier": ".models.ml",
    "KNNRegressor": ".models.ml",
    "VAE": ".models.generative",
    "VQVAE": ".models.generative",
    "VectorQuantizer": ".models.generative",
    "DDPM": ".models.generative",
    "SinusoidalTimeEmbedding": ".models.generative",
    "DenoisingMLP": ".models.generative",
    "DCGAN": ".models.generative",
    "WGANGP": ".models.generative",
    "Generator": ".models.generative",
    "Discriminator": ".models.generative",
    "VelocityMLP": ".models.generative",
    "FlowMatching": ".models.generative",
    "RectifiedFlow": ".models.generative",
    "AffineCouplingLayer": ".models.generative",
    "RealNVP": ".models.generative",
    "LoRALinear": ".models.generative",
    "LoRAAdapter": ".models.generative",
    "LatentDiffusionModel": ".models.generative",
    "LatentCrossAttentionBlock": ".models.generative",
    "ControlNet": ".models.generative",
    "ZeroConv2D": ".models.generative",
    "ControlNetBlock": ".models.generative",
    "CycleGAN": ".models.generative",
    "CycleGANGenerator": ".models.generative",
    "PatchGANDiscriminator": ".models.generative",
    "DiscreteTextDiffusion": ".models.generative",
    "ClassifierFreeGuidance": ".models.generative",
    "DiffusionInpainter": ".models.generative",
    "DiffusionTransformer": ".models.generative",
    "DiTBlock": ".models.generative",
    "AdaLNZero": ".models.generative",
    "stft": ".models.audio",
    "istft": ".models.audio",
    "spectrogram": ".models.audio",
    "mel_filterbank": ".models.audio",
    "power_to_db": ".models.audio",
    "melspectrogram": ".models.audio",
    "dct_type2": ".models.audio",
    "mfcc": ".models.audio",
    "compute_deltas": ".models.audio",
    "SpecAugment": ".models.audio",
    "Conv1D": ".models.audio",
    "DepthwiseConv1D": ".models.audio",
    "BatchNorm1D": ".models.audio",
    "Conformer": ".models.audio.architectures",
    "ConformerBlock": ".models.audio.architectures",
    "ConformerConvModule": ".models.audio.architectures",
    "AST": ".models.audio.architectures",
    "AudioSpectrogramTransformer": ".models.audio.architectures",
    "Wav2Vec2": ".models.audio.architectures",
    "Whisper": ".models.audio.architectures",
    "WhisperEncoder": ".models.audio.architectures",
    "WhisperDecoder": ".models.audio.architectures",
    "ResidualVectorQuantizer": ".models.audio",
    "VectorQuantizerStage": ".models.audio",
    "VoiceActivityDetector": ".models.audio",
    "ChokkhuModel": ".models",
    "train": ".models",
    "DBSCAN": ".models.ml",
    "KNN": ".models.ml",
    "SVM": ".models.ml",
    "DecisionTree": ".models.ml",
    "GradientBoosting": ".models.ml",
    "HierarchicalClustering": ".models.ml",
    "KMeans": ".models.ml",
    "LinearRegression": ".models.ml",
    "LogisticRegression": ".models.ml",
    "NaiveBayes": ".models.ml",
    "NeuralNetwork": ".models.ml",
    "RandomForest": ".models.ml",
    "GridWorld": ".models.rl",
    "QLearning": ".models.rl",
    "ReplayBuffer": ".models.rl",
    "PrioritizedReplayBuffer": ".models.rl",
    "DQN": ".models.rl",
    "DoubleDQN": ".models.rl",
    "DuelingDQN": ".models.rl",
    "REINFORCE": ".models.rl",
    "ActorCritic": ".models.rl",
    "PPO": ".models.rl",
    "SAC": ".models.rl",
    "EpsilonGreedyBandit": ".models.rl",
    "UCB1Bandit": ".models.rl",
    "ThompsonSamplingBandit": ".models.rl",
    "LinUCBBandit": ".models.rl",
    "DecisionTransformer": ".models.rl",
    "HindsightExperienceReplay": ".models.rl",
    "GoalConditionedDQN": ".models.rl",
    "Adam": ".models.dl",
    "AdamW": ".models.dl",
    "BatchNorm1d": ".models.dl",
    "BinaryCrossEntropyLoss": ".models.dl",
    "CrossEntropyLoss": ".models.dl",
    "Dropout": ".models.dl",
    "EarlyStopping": ".models.dl",
    "Flatten": ".models.dl",
    "GELU": ".models.dl",
    "HuberLoss": ".models.dl",
    "LayerNorm": ".models.dl",
    "LeakyReLU": ".models.dl",
    "Linear": ".models.dl",
    "Dense": ".models.dl",
    "MAELoss": ".models.dl",
    "MSELoss": ".models.dl",
    "Module": ".models.dl",
    "Parameter": ".models.dl",
    "ReLU": ".models.dl",
    "RMSProp": ".models.dl",
    "SGD": ".models.dl",
    "Sequential": ".models.dl",
    "Sigmoid": ".models.dl",
    "SiLU": ".models.dl",
    "Softmax": ".models.dl",
    "Tanh": ".models.dl",
    "AlexNet": ".models.vision.architectures",
    "AvgPool2D": ".models.vision",
    "BatchNorm2D": ".models.vision",
    "CBAM": ".models.vision",
    "AtrousConv2D": ".models.vision",
    "CIoULoss": ".models.vision",
    "DilatedConv2D": ".models.vision",
    "FeaturePyramidNetwork": ".models.vision",
    "PANet": ".models.vision",
    "DIoULoss": ".models.vision",
    "DiceLoss": ".models.vision",
    "FocalLoss": ".models.vision",
    "GIoULoss": ".models.vision",
    "TverskyLoss": ".models.vision",
    "ChannelShuffle": ".models.vision.architectures",
    "Conv2D": ".models.vision",
    "ConvNeXt": ".models.vision.architectures",
    "ConvNeXtTiny": ".models.vision.architectures",
    "ConvTranspose2D": ".models.vision",
    "DenseNet121": ".models.vision.architectures",
    "DenseNet169": ".models.vision.architectures",
    "DenseNet201": ".models.vision.architectures",
    "DepthwiseSeparableConv2D": ".models.vision",
    "EfficientNetB0": ".models.vision.architectures",
    "FCN": ".models.vision.architectures",
    "FCN8s": ".models.vision.architectures",
    "GlobalAvgPool2D": ".models.vision",
    "GoogLeNet": ".models.vision.architectures",
    "GradCAM": ".models.vision",
    "GroupedConv2D": ".models.vision",
    "InceptionV1": ".models.vision.architectures",
    "InceptionV3": ".models.vision.architectures",
    "LeNet5": ".models.vision.architectures",
    "MaxPool2D": ".models.vision",
    "MobileNetV1": ".models.vision.architectures",
    "MobileNetV2": ".models.vision.architectures",
    "MobileNetV3": ".models.vision.architectures",
    "ResNet18": ".models.vision.architectures",
    "ResNet34": ".models.vision.architectures",
    "ResNet50": ".models.vision.architectures",
    "ResNet101": ".models.vision.architectures",
    "ResNet152": ".models.vision.architectures",
    "ResNeXt50": ".models.vision.architectures",
    "ResNeXt101": ".models.vision.architectures",
    "SEBlock": ".models.vision",
    "ShuffleNetV1": ".models.vision.architectures",
    "ShuffleNetV2": ".models.vision.architectures",
    "SqueezeNet": ".models.vision.architectures",
    "SwinTransformer": ".models.vision.architectures",
    "SwinT": ".models.vision.architectures",
    "DeiT": ".models.vision.architectures",
    "DeiTTiny": ".models.vision.architectures",
    "DeepLabV3Plus": ".models.vision.architectures",
    "SegmentAnythingModel": ".models.vision.architectures",
    "UNet": ".models.vision.architectures",
    "VGG11": ".models.vision.architectures",
    "VGG13": ".models.vision.architectures",
    "VGG16": ".models.vision.architectures",
    "VGG19": ".models.vision.architectures",
    "VisionTransformer": ".models.vision.architectures",
    "ViT": ".models.vision.architectures",
    "ViTBase": ".models.vision.architectures",
    "ViTTiny": ".models.vision.architectures",
    "ZFNet": ".models.vision.architectures",
    "YOLOHead": ".models.vision",
    "SSDHead": ".models.vision",
    "RetinaNetHead": ".models.vision",
    "generate_anchor_grid": ".models.vision",
    "compute_iou": ".models.vision",
    "non_maximum_suppression": ".models.vision",
    "ByteTransformer": ".models.nlp",
    "BM25Retriever": ".models.nlp",
    "TfidfVectorizer": ".models.nlp",
    "PorterStemmer": ".models.nlp",
    "GemmaForCausalLM": ".models.nlp.architectures",
    "Gemma": ".models.nlp.architectures",
    "MistralForCausalLM": ".models.nlp.architectures",
    "Mistral": ".models.nlp.architectures",
    "DebertaForSequenceClassification": ".models.nlp.architectures",
    "DeBERTa": ".models.nlp.architectures",
    "RobertaForMaskedLM": ".models.nlp.architectures",
    "RobertaForSequenceClassification": ".models.nlp.architectures",
    "RoBERTa": ".models.nlp.architectures",
    "MoE": ".models.nlp",
    "MixtureOfExperts": ".models.nlp",
    "TopKRouter": ".models.nlp",
    "Expert": ".models.nlp",
    "SlidingWindowAttention": ".models.nlp",
    "DeepSeekMLA": ".models.nlp",
    "MultiHeadLatentAttention": ".models.nlp",
    "ALiBi": ".models.nlp",
    "BERT": ".models.nlp.architectures",
    "BPETokenizer": ".models.nlp.tokenizers",
    "BaseTokenizer": ".models.nlp.tokenizers",
    "BertForMaskedLM": ".models.nlp.architectures",
    "BertForSequenceClassification": ".models.nlp.architectures",
    "BiLSTM": ".models.nlp",
    "CharacterTokenizer": ".models.nlp.tokenizers",
    "GPT": ".models.nlp.architectures",
    "GPTForCausalLM": ".models.nlp.architectures",
    "GRU": ".models.nlp",
    "GenerationConfig": ".models.nlp",
    "GroupedQueryAttention": ".models.nlp",
    "LLaMA": ".models.nlp.architectures",
    "LSTM": ".models.nlp",
    "LearnedPositionalEmbedding": ".models.nlp",
    "LlamaForCausalLM": ".models.nlp.architectures",
    "MiniGPT": ".models.nlp.architectures",
    "MultiHeadAttention": ".models.nlp",
    "MultiQueryAttention": ".models.nlp",
    "RMSNorm": ".models.nlp",
    "RNN": ".models.nlp",
    "RoPE": ".models.nlp",
    "RotaryPositionEmbedding": ".models.nlp",
    "ScaledDotProductAttention": ".models.nlp",
    "SentencePieceTokenizer": ".models.nlp.tokenizers",
    "Seq2SeqTransformer": ".models.nlp.architectures",
    "SinusoidalPositionalEncoding": ".models.nlp",
    "SwiGLU": ".models.nlp",
    "T5": ".models.nlp.architectures",
    "TextGenerator": ".models.nlp",
    "TokenEmbedding": ".models.nlp",
    "TransformerDecoderLayer": ".models.nlp",
    "TransformerEncoderLayer": ".models.nlp",
    "WhitespaceTokenizer": ".models.nlp.tokenizers",
    "WordPieceTokenizer": ".models.nlp.tokenizers",
    "WordTokenizer": ".models.nlp.tokenizers",
    "sample_next_token": ".models.nlp",
    "RWKV6TimeMix": ".models.nlp",
    "RWKV6": ".models.nlp",
    "RetNetRetention": ".models.nlp",
    "RetNet": ".models.nlp",
    "MambaSSM": ".models.nlp",
    "Mamba": ".models.nlp",
    "DPOTrainer": ".models.nlp",
    "KTOTrainer": ".models.nlp",
    "ORPOTrainer": ".models.nlp",
    "DeepSeekMoE": ".models.nlp.architectures",
    "DeepSeekV3": ".models.nlp.architectures",
    "Qwen2_5": ".models.nlp.architectures",
    "BitLinear": ".models.nlp.architectures",
    "BitNet158": ".models.nlp.architectures",
    "SpeculativeDecoder": ".models.nlp",
    "StructuredJSONDecoder": ".models.nlp",
    "PagedKVCache": ".models.nlp",
    "PagedAttention": ".models.nlp",
    "ContinuousBatcher": ".models.nlp",
    "Mamba2SSD": ".models.nlp",
    "JambaHybridBlock": ".models.nlp",
    "GCN": ".models.gnn",
    "GAT": ".models.gnn",
    "GraphSAGE": ".models.gnn",
    "GIN": ".models.gnn",
    "GCNLayer": ".models.gnn",
    "GATLayer": ".models.gnn",
    "GraphSAGELayer": ".models.gnn",
    "GINLayer": ".models.gnn",
    "normalize_adjacency": ".models.gnn",
    "dense_to_edge_index": ".models.gnn",
    "edge_index_to_dense": ".models.gnn",
    "global_pool": ".models.gnn",
    "LaplacianPositionalEncoding": ".models.gnn",
    "GraphormerLayer": ".models.gnn",
    "Graphormer": ".models.gnn",
    "RGCNLayer": ".models.gnn",
    "RGCNClassifier": ".models.gnn",
    "EGNNLayer": ".models.gnn",
    "EGNN": ".models.gnn",
    "TemporalGraphNetwork": ".models.gnn",
    "HypergraphConvolution": ".models.gnn",
    "HGNN": ".models.gnn",
    "HeteroGCN": ".models.gnn",
    "SpatioTemporalGCN": ".models.gnn",
    "DiffusionPolicy": ".models.robotics",
    "RecurrentWorldModel": ".models.robotics",
    "MPPITrajectoryOptimizer": ".models.robotics",
    "QMIX": ".models.marl",
    "VDN": ".models.marl",
    "NashEquilibriumSolver": ".models.marl",
    "ReplicatorDynamics": ".models.marl",
    "CombinatorialAuction": ".models.marl",
    "SupportVectorDataDescription": ".models.anomaly",
    "GenomicTokenizer": ".models.bio",
    "GenomicBERT": ".models.bio",
    "ProteinContactMap": ".models.bio",
    "DifferentiableLogicEngine": ".models.neurosymbolic",
    "RotatE": ".models.neurosymbolic",
    "TransE": ".models.neurosymbolic",
    "DifferentiableILP": ".models.neurosymbolic",
    "decompose_series": ".models.timeseries",
    "create_lag_matrix": ".models.timeseries",
    "difference": ".models.timeseries",
    "inverse_difference": ".models.timeseries",
    "ARIMA": ".models.timeseries",
    "ExponentialSmoothing": ".models.timeseries",
    "NBEATS": ".models.timeseries",
    "NBEATSBlock": ".models.timeseries",
    "NHITS": ".models.timeseries",
    "NHITSBlock": ".models.timeseries",
    "PatchTST": ".models.timeseries",
    "ConformalPredictor": ".models.timeseries",
    "conformal_interval": ".models.timeseries",
    "MatrixProfile": ".models.timeseries",
    "find_motifs": ".models.timeseries",
    "find_discords": ".models.timeseries",
    "ExtendedKalmanFilter": ".models.timeseries",
    "UnscentedKalmanFilter": ".models.timeseries",
    "HNSWIndex": ".models.retrieval",
    "IVFPQIndex": ".models.retrieval",
    "RandomHyperplaneLSH": ".models.retrieval",
    "MinHashLSH": ".models.retrieval",
    "BM25Plus": ".models.retrieval",
    "OkapiBM25": ".models.retrieval",
    "HybridReranker": ".models.retrieval",
    "DenseRetriever": ".models.retrieval",
    "reciprocal_rank_fusion": ".models.retrieval",
    "SVDRecommender": ".models.recommendation",
    "SVDPlusPlus": ".models.recommendation",
    "ImplicitALS": ".models.recommendation",
    "NMFRecommender": ".models.recommendation",
    "BayesianPersonalizedRanking": ".models.recommendation",
    "NeuralCollaborativeFiltering": ".models.recommendation",
    "WideAndDeep": ".models.recommendation",
    "DeepFM": ".models.recommendation",
    "DLRM": ".models.recommendation",
    "SASRec": ".models.recommendation",
    "GRU4Rec": ".models.recommendation",
    "hit_rate_at_k": ".models.recommendation",
    "ndcg_at_k": ".models.recommendation",
    "mrr_at_k": ".models.recommendation",
    "precision_at_k": ".models.recommendation",
    "recall_at_k": ".models.recommendation",
    "map_at_k": ".models.recommendation",
    "NOTEARSCausalDiscovery": ".models.causal",
    "PCAlgorithm": ".models.causal",
    "PropensityModel": ".models.causal",
    "PropensityScoreMatching": ".models.causal",
    "InverseProbabilityWeighting": ".models.causal",
    "DoublyRobustLearner": ".models.causal",
    "SLearner": ".models.causal",
    "TLearner": ".models.causal",
    "XLearner": ".models.causal",
    "TwoModelUplift": ".models.causal",
    "ClassTransformationUplift": ".models.causal",
    "qini_curve": ".models.causal",
    "qini_score": ".models.causal",
    "cumulative_gain_curve": ".models.causal",
    "uplift_at_k": ".models.causal",
    "KaplanMeierFitter": ".models.survival",
    "NelsonAalenFitter": ".models.survival",
    "logrank_test": ".models.survival",
    "CoxPHRegression": ".models.survival",
    "DeepSurv": ".models.survival",
    "concordance_index": ".models.survival",
    "brier_score_loss": ".models.survival",
    "integrated_brier_score": ".models.survival",
    "CLIP": ".models.multimodal",
    "CLIPVisionEncoder": ".models.multimodal",
    "CLIPTextEncoder": ".models.multimodal",
    "SigLIP": ".models.multimodal",
    "CLAP": ".models.multimodal",
    "CLAPAudioEncoder": ".models.multimodal",
    "CLAPTextEncoder": ".models.multimodal",
    "LLaVALinearProjector": ".models.multimodal",
    "LLaVAMLPProjector": ".models.multimodal",
    "PerceiverResampler": ".models.multimodal",
    "DifferentiableParticleFluid": ".models.sciml",
    "PINN": ".models.sciml",
    "BurgersPINN": ".models.sciml",
    "HeatPINN": ".models.sciml",
    "WavePINN": ".models.sciml",
    "HarmonicOscillatorPINN": ".models.sciml",
    "SymbolicRegressor": ".models.sciml",
    "NeuralODE": ".models.sciml",
    "TrajectoryBalanceGFlowNet": ".models.generative",
    "WassersteinBarycenter": ".optimal_transport",
    "wasserstein_barycenter": ".optimal_transport",
    "SinkhornDivergence": ".optimal_transport",
    "SinkhornOptimalTransport": ".optimal_transport",
    "sinkhorn_distance": ".optimal_transport",
    "OptNet": ".optimization",
    "KFAC": ".optimization",
    "FollowTheRegularizedLeader": ".optimization",
    "HedgeAlgorithm": ".optimization",
    "MultiTaskDispatcher": ".pipeline",
    "MultiTaskPipelineResult": ".pipeline",
    "dispatch_pipeline": ".pipeline",
    "ChokkhuPipeline": ".pipeline",
    "PipelineResult": ".pipeline",
    "TransformationState": ".pipeline",
    "pipeline": ".pipeline",
    "DeepFeatureSynthesizer": ".pipeline",
    "StackingPipeline": ".pipeline",
    "Any": ".transformation",
    "Tuple": ".preprocessing",
    "BinaryEncoder": ".preprocessing",
    "FrequencyEncoder": ".preprocessing",
    "LabelEncoder": ".preprocessing",
    "OneHotEncoder": ".preprocessing",
    "OrdinalEncoder": ".preprocessing",
    "TargetEncoder": ".preprocessing",
    "ANOVASelector": ".preprocessing",
    "CorrelationFilterSelector": ".preprocessing",
    "MutualInfoSelector": ".preprocessing",
    "RFESelector": ".preprocessing",
    "VarianceThresholdSelector": ".preprocessing",
    "L2Scaler": ".preprocessing",
    "MaxAbsScaler": ".preprocessing",
    "MinMaxScaler": ".preprocessing",
    "PowerScaler": ".preprocessing",
    "QuantileScaler": ".preprocessing",
    "RobustScaler": ".preprocessing",
    "StandardScaler": ".preprocessing",
    "get_scaler": ".preprocessing",
    "preprocess": ".preprocessing",
    "PreprocessorState": ".preprocessing",
    "DP_SGD": ".privacy",
    "GaussianMechanism": ".privacy",
    "LaplaceMechanism": ".privacy",
    "FederatedClient": ".privacy",
    "FederatedServer": ".privacy",
    "SISARetraining": ".privacy",
    "FisherScrubbing": ".privacy",
    "SCRUB": ".privacy",
    "NullspaceConceptScrubbing": ".privacy",
    "QuantumCircuit": ".quantum",
    "QuantumKernel": ".quantum",
    "VariationalQuantumClassifier": ".quantum",
    "NeuralSort": ".ranking",
    "DifferentiableRankingLoss": ".ranking",
    "LambdaMART": ".ranking",
    "ListNet": ".ranking",
    "HTMLReportBuilder": ".reports",
    "create_diagnostic_dashboard": ".reports",
    "StatisticalTextWatermark": ".safety",
    "RefusalDirectionProbe": ".safety",
    "Union": ".splitting",
    "kfold": ".splitting",
    "time_series_split": ".splitting",
    "train_test_split": ".splitting",
    "split": ".splitting",
    "PersistenceDiagram": ".tda",
    "bottleneck_distance": ".tda",
    "VietorisRipsComplex": ".tda",
    "PersistenceLandscape": ".tda",
    "PersistenceImage": ".tda",
    "ImageAugmenter": ".transformation",
    "BinningTransformer": ".transformation",
    "LogTransformer": ".transformation",
    "PolynomialFeatures": ".transformation",
    "PCA": ".transformation",
    "TruncatedSVD": ".transformation",
    "ADASYN": ".transformation",
    "SMOTE": ".transformation",
    "RandomOverSampler": ".transformation",
    "RandomUnderSampler": ".transformation",
    "SMOTETomek": ".transformation",
    "TSNE": ".transformation",
    "UMAP": ".transformation",
    "SymbolicFeatureSynthesizer": ".transformation",
    "SymbolicProgram": ".transformation",
    "transform": ".transformation",
    "LDA": ".transformation",
    "ConformalizedQuantileRegression": ".uncertainty",
    "QuantileRegressor": ".uncertainty",
    "InvalidURLException": ".utils",
    "get_window": ".models.audio",
    "im2col1d": ".models.audio",
    "TwoStageLeastSquares": ".models.causal",
    "InstrumentalGMM": ".models.causal",
    "DoubleMLPLR": ".models.causal",
    "RLearner": ".models.causal",
    "Loss": ".models.dl",
    "Optimizer": ".models.dl",
    "LRScheduler": ".models.dl",
    "StepLR": ".models.dl",
    "CosineAnnealingLR": ".models.dl",
    "Callback": ".models.dl",
    "DirectFeedbackAlignmentNetwork": ".models.dl",
    "DifferenceTargetPropagationNetwork": ".models.dl",
    "DecoupledSyntheticGradientLayer": ".models.dl",
    "ConsistencyModel": ".models.generative",
    "ConsistencyMLP": ".models.generative",
    "OptimalTransportFlowMatching": ".models.generative",
    "ReflowMatching": ".models.generative",
    "EnEquivariantLayer": ".models.geometric",
    "EnEquivariantGNN": ".models.geometric",
    "CliffordMultivector": ".models.geometric",
    "CliffordLinear": ".models.geometric",
    "CliffordGANN": ".models.geometric",
    "geometric_product": ".models.geometric",
    "GraphCL": ".models.gnn",
    "GRACE": ".models.gnn",
    "Individual": ".models.meta",
    "MAPElitesResult": ".models.meta",
    "ProgramSynthesizer": ".models.neurosymbolic",
    "DSLGrammar": ".models.neurosymbolic",
    "MCTSNode": ".models.nlp.reasoning",
    "MonteCarloTreeSearchReasoning": ".models.nlp.reasoning",
    "ProcessRewardModel": ".models.nlp.reasoning",
    "STaR": ".models.nlp.reasoning",
    "ReflexionLoop": ".models.nlp.reasoning",
    "RobotArmKinematics": ".models.robotics",
    "ActionTokenizer": ".models.robotics",
    "TemporalEnsembler": ".models.robotics",
    "ActionChunkingTransformer": ".models.robotics",
    "OpenVLAPolicy": ".models.robotics",
    "SpectralConv2d": ".models.sciml",
    "FourierNeuralOperator2D": ".models.sciml",
    "SparseGaussianProcessRegression": ".models.sciml",
    "VariationalSparseGP": ".models.sciml",
    "ParticleFilter": ".models.timeseries",
    "RaoBlackwellizedParticleFilter": ".models.timeseries",
    "BottleneckResidualBlock": ".models.vision.architectures",
    "ConvNeXtBlock": ".models.vision.architectures",
    "DeiTBase": ".models.vision.architectures",
    "DeiTSmall": ".models.vision.architectures",
    "DenseBlock": ".models.vision.architectures",
    "FireModule": ".models.vision.architectures",
    "InceptionModule": ".models.vision.architectures",
    "InvertedResidual": ".models.vision.architectures",
    "MBConv": ".models.vision.architectures",
    "PatchEmbedding": ".models.vision.architectures",
    "ResidualBlock": ".models.vision.architectures",
    "SwinBase": ".models.vision.architectures",
    "SwinSmall": ".models.vision.architectures",
    "TransitionBlock": ".models.vision.architectures",
    "ChannelAttention": ".models.vision",
    "SpatialAttention": ".models.vision",
    "FPNPyramid": ".models.vision",
    "TNet": ".models.vision_3d",
    "PointNetClassifier": ".models.vision_3d",
    "PointNetSegmenter": ".models.vision_3d",
    "PointNet2Classifier": ".models.vision_3d",
    "SetAbstractionModule": ".models.vision_3d",
    "farthest_point_sampling": ".models.vision_3d",
    "ball_query": ".models.vision_3d",
    "PositionalEncoder": ".models.vision_3d",
    "NeRFMLP": ".models.vision_3d",
    "volume_render": ".models.vision_3d",
    "generate_camera_rays": ".models.vision_3d",
    "GaussianSplatting3D": ".models.vision_3d",
    "quaternion_to_rotation_matrix": ".models.vision_3d",
    "ASPPModule": ".models.vision.architectures",
    "SAMTwoWayAttentionBlock": ".models.vision.architectures",
    "Tool": ".models.nlp.agents",
    "ToolParameter": ".models.nlp.agents",
    "ToolRegistry": ".models.nlp.agents",
    "ReActAgent": ".models.nlp.agents",
    "AgentAction": ".models.nlp.agents",
    "AgentFinish": ".models.nlp.agents",
    "AgentStep": ".models.nlp.agents",
    "ChainOfThought": ".models.nlp.agents",
    "TreeOfThoughts": ".models.nlp.agents",
    "GraphOfThoughts": ".models.nlp.agents",
    "MultiAgentCoordinator": ".models.nlp.agents",
    "ReflexionEngine": ".models.nlp.agents",
    "SelfConsistency": ".models.nlp.agents",
    "Tensor": ".core.tensor",
    "Function": ".core.tensor",
    "concat": ".core.tensor",
}

_SUBMODULES: set[str] = set(
    [
        "automl",
        "cleaning",
        "clustering",
        "compression",
        "continual",
        "core",
        "data",
        "eda",
        "evaluation",
        "explainability",
        "fairness",
        "geometry",
        "geospatial",
        "hdc",
        "information",
        "io",
        "models",
        "optimal_transport",
        "optimization",
        "pipeline",
        "preprocessing",
        "privacy",
        "quantum",
        "ranking",
        "reports",
        "safety",
        "splitting",
        "tda",
        "transformation",
        "uncertainty",
        "utils",
    ]
)


def __getattr__(name: str) -> Any:
    if name in _ALIASES:
        module_path, actual_name = _ALIASES[name]
        module = importlib.import_module(module_path, package=__name__)
        val = getattr(module, actual_name)
        globals()[name] = val
        return val
    if name in _LAZY_IMPORTS:
        module_path = _LAZY_IMPORTS[name]
        module = importlib.import_module(module_path, package=__name__)
        val = getattr(module, name)
        globals()[name] = val
        return val
    if name in _SUBMODULES:
        module = importlib.import_module(f".{name}", package=__name__)
        globals()[name] = module
        return module
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")


def __dir__() -> List[str]:
    return sorted(
        list(globals().keys())
        + list(_LAZY_IMPORTS.keys())
        + list(_ALIASES.keys())
        + list(_SUBMODULES)
    )


__all__ = sorted(
    list(_LAZY_IMPORTS.keys())
    + list(_ALIASES.keys())
    + list(_SUBMODULES)
    + ["__version__", "__author__"]
)
