from __future__ import annotations

from typing import Any, Optional

__version__ = "0.8.0"
__author__ = "tamimystic"

from .cleaning import clean
from .eda import ImageEDA
from .eda import tabular as tabular_fn
from .io import load, save
from .preprocessing import (
    PowerScaler,
    QuantileScaler,
    RFESelector,
    StandardScaler,
    MinMaxScaler,
    RobustScaler,
    preprocess,
)
from .splitting import split
from .transformation import (
    LDA,
    PCA,
    SMOTE,
    TSNE,
    ImageAugmenter,
    LinearDiscriminantAnalysis,
    PolynomialFeatures,
    transform,
)
from .core.tensor import Tensor
from .models import (
    Discriminator,
    Generator,
    WGANGP,
    DCGAN,
    DenoisingMLP,
    SinusoidalTimeEmbedding,
    DDPM,
    VectorQuantizer,
    VQVAE,
    VAE,
    Wav2Vec2,
    AudioSpectrogramTransformer,
    AST,
    ConformerConvModule,
    ConformerBlock,
    Conformer,
    BatchNorm1D,
    DepthwiseConv1D,
    Conv1D,
    SpecAugment,
    compute_deltas,
    mfcc,
    dct_type2,
    melspectrogram,
    power_to_db,
    mel_filterbank,
    spectrogram,
    istft,
    stft,
    BM25Retriever,
    TfidfVectorizer,
    PorterStemmer,
    GemmaForCausalLM,
    Gemma,
    MistralForCausalLM,
    Mistral,
    DebertaForSequenceClassification,
    DeBERTa,
    RobertaForMaskedLM,
    RobertaForSequenceClassification,
    RoBERTa,
    MoE,
    MixtureOfExperts,
    TopKRouter,
    Expert,
    SlidingWindowAttention,
    DeepSeekMLA,
    MultiHeadLatentAttention,
    AlexNet,
    AvgPool2D,
    BatchNorm2D,
    CBAM,
    AtrousConv2D,
    CIoULoss,
    DilatedConv2D,
    FeaturePyramidNetwork,
    PANet,
    DIoULoss,
    DiceLoss,
    FocalLoss,
    GIoULoss,
    TverskyLoss,
    ChannelShuffle,
    Conv2D,
    ConvNeXt,
    ConvNeXtTiny,
    ConvTranspose2D,
    Dense,
    DenseNet121,
    DenseNet169,
    DenseNet201,
    DepthwiseSeparableConv2D,
    EfficientNetB0,
    FCN,
    FCN8s,
    GlobalAvgPool2D,
    GoogLeNet,
    GradCAM,
    GroupedConv2D,
    InceptionV1,
    InceptionV3,
    LeNet5,
    Linear,
    MaxPool2D,
    MobileNetV1,
    MobileNetV2,
    MobileNetV3,
    NeuralNetwork,
    ResNet18,
    ResNet34,
    ResNet50,
    ResNet101,
    ResNet152,
    ResNeXt50,
    ResNeXt101,
    SEBlock,
    Sequential,
    ShuffleNetV1,
    ShuffleNetV2,
    SqueezeNet,
    SwinTransformer,
    SwinT,
    DeiT,
    DeiTTiny,
    UNet,
    VGG11,
    VGG13,
    VGG16,
    VGG19,
    VisionTransformer,
    ViT,
    ViTBase,
    ViTTiny,
    ZFNet,
    YOLOHead,
    SSDHead,
    RetinaNetHead,
    generate_anchor_grid,
    # NLP
    BERT,
    BPETokenizer,
    BaseTokenizer,
    BertForMaskedLM,
    BertForSequenceClassification,
    BiLSTM,
    CharacterTokenizer,
    GPT,
    GPTForCausalLM,
    GRU,
    GenerationConfig,
    GroupedQueryAttention,
    LLaMA,
    LSTM,
    LearnedPositionalEmbedding,
    LlamaForCausalLM,
    MiniGPT,
    MultiHeadAttention,
    RMSNorm,
    RNN,
    RoPE,
    SentencePieceTokenizer,
    Seq2SeqTransformer,
    SinusoidalPositionalEncoding,
    SwiGLU,
    T5,
    TextGenerator,
    TokenEmbedding,
    WhitespaceTokenizer,
    WordPieceTokenizer,
    WordTokenizer,
    RWKV6,
    RetNet,
    Mamba,
    DeepSeekV3,
    Qwen2_5,
    BitNet158,
    DPOTrainer,
    KTOTrainer,
    ORPOTrainer,
    train,
)
from .evaluation import (
    EvaluationResult,
    evaluate,
    accuracy_score,
    log_loss,
    mean_squared_error,
    r2_score,
    roc_auc_score,
    pr_auc_score,
)
from .explainability import (
    ExplanationResult,
    explain,
    IntegratedGradients,
    SmoothGrad,
    DeepLIFT,
)

from .pipeline import PipelineResult, TransformationState, pipeline


class EDAWrapper:
    @staticmethod
    def image(
        dataset_path: str,
        save_reports: bool = False,
        save_dir: Optional[str] = None,
    ) -> Any:
        if save_reports and save_dir is None:
            save_dir = "chokkhu_outputs/image_reports"
        return ImageEDA(
            dataset_path=dataset_path, save_reports=save_reports, save_dir=save_dir
        )

    @staticmethod
    def tabular(
        dataset_path: str,
        save_reports: bool = False,
        save_dir: Optional[str] = None,
        target_col: Optional[str] = None,
    ) -> Any:
        if save_reports and save_dir is None:
            save_dir = "chokkhu_outputs/tabular_reports"
        return tabular_fn(
            dataset_path=dataset_path,
            target_col=target_col,
            save_reports=save_reports,
            save_dir=save_dir,
        )


eda = EDAWrapper()

from .models.gnn import (
    GCN,
    GAT,
    GraphSAGE,
    GIN,
    normalize_adjacency,
    LaplacianPositionalEncoding,
    Graphormer,
    RGCNClassifier,
    EGNN,
    TemporalGraphNetwork,
    HGNN,
)

from .models.rl import (
    DQN,
    DoubleDQN,
    DuelingDQN,
    ReplayBuffer,
    PrioritizedReplayBuffer,
    REINFORCE,
    ActorCritic,
    PPO,
    SAC,
    EpsilonGreedyBandit,
    UCB1Bandit,
    ThompsonSamplingBandit,
    LinUCBBandit,
    DecisionTransformer,
)

from .models.timeseries import (
    ARIMA,
    ExponentialSmoothing,
    NBEATS,
    NHITS,
    PatchTST,
    decompose_series,
)

from .automl import (
    AutoTrainer,
    AutoMLResult,
    auto_train,
    BayesianOptimization,
    Hyperband,
)

from .models.retrieval import (
    HNSWIndex,
    IVFPQIndex,
    RandomHyperplaneLSH,
    MinHashLSH,
    DenseRetriever,
    reciprocal_rank_fusion,
)

from .models.recommendation import (
    SVDRecommender,
    SVDPlusPlus,
    ImplicitALS,
    NMFRecommender,
    BayesianPersonalizedRanking,
    NeuralCollaborativeFiltering,
    WideAndDeep,
    DeepFM,
    DLRM,
    SASRec,
    GRU4Rec,
    hit_rate_at_k,
    ndcg_at_k,
    mrr_at_k,
    precision_at_k,
    recall_at_k,
    map_at_k,
)

from .models.causal import (
    PropensityModel,
    PropensityScoreMatching,
    InverseProbabilityWeighting,
    DoublyRobustLearner,
    SLearner,
    TLearner,
    XLearner,
    TwoModelUplift,
    ClassTransformationUplift,
    qini_curve,
    qini_score,
    cumulative_gain_curve,
    uplift_at_k,
)

from .models.survival import (
    KaplanMeierFitter,
    NelsonAalenFitter,
    logrank_test,
    CoxPHRegression,
    DeepSurv,
    concordance_index,
    brier_score_loss,
    integrated_brier_score,
)

from .models.multimodal import (
    CLIP,
    CLIPVisionEncoder,
    CLIPTextEncoder,
    SigLIP,
    LLaVALinearProjector,
    LLaVAMLPProjector,
    PerceiverResampler,
)

from .models.sciml import (
    PINN,
    BurgersPINN,
    HeatPINN,
    WavePINN,
    HarmonicOscillatorPINN,
    SymbolicRegressor,
    NeuralODE,
)

from .fairness import (
    demographic_parity_difference,
    demographic_parity_ratio,
    equal_opportunity_difference,
    equalized_odds_difference,
    disparate_impact_ratio,
    theil_index,
    fairness_report,
    ReweighingTransformer,
    DisparateImpactRemover,
    ThresholdOptimizer,
)

from .compression import (
    UniformQuantizer,
    PostTrainingQuantizer,
    QuantizedLinear,
    MagnitudePruner,
    GlobalMagnitudePruner,
    KnowledgeDistiller,
    FeatureDistiller,
)

from .models.vision_3d import (
    TNet,
    PointNetClassifier,
    PointNetSegmenter,
    PointNet2Classifier,
    SetAbstractionModule,
    farthest_point_sampling,
    ball_query,
    PositionalEncoder,
    NeRFMLP,
    volume_render,
    generate_camera_rays,
    GaussianSplatting3D,
    quaternion_to_rotation_matrix,
)

from .models.nlp.agents import (
    Tool,
    ToolParameter,
    ToolRegistry,
    ReActAgent,
    AgentAction,
    AgentFinish,
    AgentStep,
    ChainOfThought,
    TreeOfThoughts,
    GraphOfThoughts,
    MultiAgentCoordinator,
    ReflexionEngine,
    SelfConsistency,
)

__all__ = [
    "Discriminator",
    "Generator",
    "WGANGP",
    "DCGAN",
    "DenoisingMLP",
    "SinusoidalTimeEmbedding",
    "DDPM",
    "VectorQuantizer",
    "VQVAE",
    "VAE",
    "Wav2Vec2",
    "AudioSpectrogramTransformer",
    "AST",
    "ConformerConvModule",
    "ConformerBlock",
    "Conformer",
    "BatchNorm1D",
    "DepthwiseConv1D",
    "Conv1D",
    "SpecAugment",
    "compute_deltas",
    "mfcc",
    "dct_type2",
    "melspectrogram",
    "power_to_db",
    "mel_filterbank",
    "spectrogram",
    "istft",
    "stft",
    "BM25Retriever",
    "TfidfVectorizer",
    "PorterStemmer",
    "GemmaForCausalLM",
    "Gemma",
    "MistralForCausalLM",
    "Mistral",
    "DebertaForSequenceClassification",
    "DeBERTa",
    "RobertaForMaskedLM",
    "RobertaForSequenceClassification",
    "RoBERTa",
    "MoE",
    "MixtureOfExperts",
    "TopKRouter",
    "Expert",
    "SlidingWindowAttention",
    "DeepSeekMLA",
    "MultiHeadLatentAttention",
    "eda",
    "load",
    "save",
    "clean",
    "preprocess",
    "transform",
    "split",
    "PCA",
    "LDA",
    "LinearDiscriminantAnalysis",
    "TSNE",
    "SMOTE",
    "ImageAugmenter",
    "PolynomialFeatures",
    "train",
    "evaluate",
    "EvaluationResult",
    "explain",
    "IntegratedGradients",
    "SmoothGrad",
    "DeepLIFT",
    "ExplanationResult",
    "pipeline",
    "PipelineResult",
    "TransformationState",
    "NeuralNetwork",
    "Tensor",
    "Sequential",
    "Linear",
    "Dense",
    # Vision
    "Conv2D",
    "MaxPool2D",
    "AvgPool2D",
    "GlobalAvgPool2D",
    "DepthwiseSeparableConv2D",
    "GroupedConv2D",
    "ChannelShuffle",
    "ConvTranspose2D",
    "BatchNorm2D",
    "SEBlock",
    "CBAM",
    "AtrousConv2D",
    "CIoULoss",
    "DilatedConv2D",
    "FeaturePyramidNetwork",
    "PANet",
    "DIoULoss",
    "DiceLoss",
    "FocalLoss",
    "GIoULoss",
    "TverskyLoss",
    "LeNet5",
    "AlexNet",
    "ZFNet",
    "YOLOHead",
    "SSDHead",
    "RetinaNetHead",
    "generate_anchor_grid",
    "VGG11",
    "VGG13",
    "VGG16",
    "VGG19",
    "GoogLeNet",
    "InceptionV1",
    "InceptionV3",
    "ResNet18",
    "ResNet34",
    "ResNet50",
    "ResNet101",
    "ResNet152",
    "ResNeXt50",
    "ResNeXt101",
    "DenseNet121",
    "DenseNet169",
    "DenseNet201",
    "SqueezeNet",
    "SwinTransformer",
    "SwinT",
    "DeiT",
    "DeiTTiny",
    "MobileNetV1",
    "MobileNetV2",
    "MobileNetV3",
    "ShuffleNetV1",
    "ShuffleNetV2",
    "EfficientNetB0",
    "ConvNeXt",
    "ConvNeXtTiny",
    "UNet",
    "FCN",
    "FCN8s",
    "VisionTransformer",
    "ViT",
    "ViTTiny",
    "ViTBase",
    "GradCAM",
    # NLP
    "BaseTokenizer",
    "CharacterTokenizer",
    "WordTokenizer",
    "WhitespaceTokenizer",
    "BPETokenizer",
    "WordPieceTokenizer",
    "SentencePieceTokenizer",
    "TokenEmbedding",
    "SinusoidalPositionalEncoding",
    "LearnedPositionalEmbedding",
    "RoPE",
    "RNN",
    "LSTM",
    "BiLSTM",
    "GRU",
    "MultiHeadAttention",
    "GroupedQueryAttention",
    "RMSNorm",
    "SwiGLU",
    "BERT",
    "BertForSequenceClassification",
    "BertForMaskedLM",
    "GPT",
    "MiniGPT",
    "GPTForCausalLM",
    "LLaMA",
    "LlamaForCausalLM",
    "Seq2SeqTransformer",
    "T5",
    "GenerationConfig",
    "RWKV6",
    "RetNet",
    "Mamba",
    "DeepSeekV3",
    "Qwen2_5",
    "BitNet158",
    "DPOTrainer",
    "KTOTrainer",
    "ORPOTrainer",
    # Preprocessing & Metrics
    "StandardScaler",
    "MinMaxScaler",
    "RobustScaler",
    "PowerScaler",
    "QuantileScaler",
    "RFESelector",
    "accuracy_score",
    "roc_auc_score",
    "pr_auc_score",
    "log_loss",
    "mean_squared_error",
    "r2_score",
    # GNN
    "GCN",
    "GAT",
    "GraphSAGE",
    "GIN",
    "normalize_adjacency",
    "LaplacianPositionalEncoding",
    "Graphormer",
    "RGCNClassifier",
    "EGNN",
    "TemporalGraphNetwork",
    "HGNN",
    # Reinforcement Learning
    "DQN",
    "DoubleDQN",
    "DuelingDQN",
    "ReplayBuffer",
    "PrioritizedReplayBuffer",
    "REINFORCE",
    "ActorCritic",
    "PPO",
    "SAC",
    "EpsilonGreedyBandit",
    "UCB1Bandit",
    "ThompsonSamplingBandit",
    "LinUCBBandit",
    "DecisionTransformer",
    # Time Series
    "ARIMA",
    "ExponentialSmoothing",
    "NBEATS",
    "NHITS",
    "PatchTST",
    "decompose_series",
    # AutoML
    "AutoTrainer",
    "AutoMLResult",
    "auto_train",
    "BayesianOptimization",
    "Hyperband",
    # Vector Retrieval
    "HNSWIndex",
    "IVFPQIndex",
    "RandomHyperplaneLSH",
    "MinHashLSH",
    "DenseRetriever",
    "reciprocal_rank_fusion",
    # Recommendation Systems
    "SVDRecommender",
    "SVDPlusPlus",
    "ImplicitALS",
    "NMFRecommender",
    "BayesianPersonalizedRanking",
    "NeuralCollaborativeFiltering",
    "WideAndDeep",
    "DeepFM",
    "DLRM",
    "SASRec",
    "GRU4Rec",
    "hit_rate_at_k",
    "ndcg_at_k",
    "mrr_at_k",
    "precision_at_k",
    "recall_at_k",
    "map_at_k",
    # Causal Inference & Uplift
    "PropensityModel",
    "PropensityScoreMatching",
    "InverseProbabilityWeighting",
    "DoublyRobustLearner",
    "SLearner",
    "TLearner",
    "XLearner",
    "TwoModelUplift",
    "ClassTransformationUplift",
    "qini_curve",
    "qini_score",
    "cumulative_gain_curve",
    "uplift_at_k",
    # Survival Analysis & Reliability
    "KaplanMeierFitter",
    "NelsonAalenFitter",
    "logrank_test",
    "CoxPHRegression",
    "DeepSurv",
    "concordance_index",
    "brier_score_loss",
    "integrated_brier_score",
    # Multi-Modal Vision-Language
    "CLIP",
    "CLIPVisionEncoder",
    "CLIPTextEncoder",
    "SigLIP",
    "LLaVALinearProjector",
    "LLaVAMLPProjector",
    "PerceiverResampler",
    # Scientific Machine Learning & PINNs
    "PINN",
    "BurgersPINN",
    "HeatPINN",
    "WavePINN",
    "HarmonicOscillatorPINN",
    "SymbolicRegressor",
    "NeuralODE",
    # Algorithmic Fairness & Bias Mitigation
    "demographic_parity_difference",
    "demographic_parity_ratio",
    "equal_opportunity_difference",
    "equalized_odds_difference",
    "disparate_impact_ratio",
    "theil_index",
    "fairness_report",
    "ReweighingTransformer",
    "DisparateImpactRemover",
    "ThresholdOptimizer",
    # Edge AI, Quantization & Compression
    "UniformQuantizer",
    "PostTrainingQuantizer",
    "QuantizedLinear",
    "MagnitudePruner",
    "GlobalMagnitudePruner",
    "KnowledgeDistiller",
    "FeatureDistiller",
    # 3D Computer Vision, Point Clouds & Neural Radiance (NeRF & 3DGS)
    "TNet",
    "PointNetClassifier",
    "PointNetSegmenter",
    "PointNet2Classifier",
    "SetAbstractionModule",
    "farthest_point_sampling",
    "ball_query",
    "PositionalEncoder",
    "NeRFMLP",
    "volume_render",
    "generate_camera_rays",
    "GaussianSplatting3D",
    "quaternion_to_rotation_matrix",
    # Autonomous AI Agents & Execution Engines
    "Tool",
    "ToolParameter",
    "ToolRegistry",
    "ReActAgent",
    "AgentAction",
    "AgentFinish",
    "AgentStep",
    "ChainOfThought",
    "TreeOfThoughts",
    "GraphOfThoughts",
    "MultiAgentCoordinator",
    "ReflexionEngine",
    "SelfConsistency",
]
