from __future__ import annotations
from .models.nlp.reasoning import (
    MCTSNode,
    MonteCarloTreeSearchReasoning,
    ProcessRewardModel,
    STaR,
    ReflexionLoop,
)
from .explainability import (
    TopKSAE,
    JumpReLU,
    ActivationPatching,
)
from .privacy import (
    SISARetraining,
    FisherScrubbing,
    SCRUB,
    NullspaceConceptScrubbing,
)
from .models.merging import (
    TIESMerging,
    DARE,
    SLERP,
    RegMean,
    FrankWolfeEnsemble,
)

from typing import Any, Optional

__version__ = "1.5.7"
__author__ = "tamimystic"

from .cleaning import clean, LocalOutlierFactor, EllipticEnvelope
from .eda import ImageEDA
from .eda import tabular as tabular_fn
from .io import load, save
from .preprocessing import (
    PowerScaler,
    QuantileScaler,
    RFESelector,
    StandardScaler,
    MinMaxScaler,
    RobustScaler,
    preprocess,
)
from .splitting import split
from .transformation import (
    LDA,
    PCA,
    SMOTE,
    TSNE,
    UMAP,
    ImageAugmenter,
    LinearDiscriminantAnalysis,
    PolynomialFeatures,
    transform,
)
from .core.tensor import Tensor
from .models import (
    Discriminator,
    Generator,
    WGANGP,
    DCGAN,
    DenoisingMLP,
    SinusoidalTimeEmbedding,
    DDPM,
    ControlNet,
    ZeroConv2D,
    ControlNetBlock,
    CycleGAN,
    CycleGANGenerator,
    PatchGANDiscriminator,
    DiscreteTextDiffusion,
    ClassifierFreeGuidance,
    DiffusionInpainter,
    DiffusionTransformer,
    DiTBlock,
    AdaLNZero,
    VectorQuantizer,
    VQVAE,
    VAE,
    VelocityMLP,
    FlowMatching,
    RectifiedFlow,
    AffineCouplingLayer,
    RealNVP,
    LoRALinear,
    LoRAAdapter,
    LatentDiffusionModel,
    LatentCrossAttentionBlock,
    Wav2Vec2,
    Whisper,
    WhisperEncoder,
    WhisperDecoder,
    ResidualVectorQuantizer,
    VectorQuantizerStage,
    VoiceActivityDetector,
    AudioSpectrogramTransformer,
    AST,
    ConformerConvModule,
    ConformerBlock,
    Conformer,
    BatchNorm1D,
    DepthwiseConv1D,
    Conv1D,
    SpecAugment,
    compute_deltas,
    mfcc,
    dct_type2,
    melspectrogram,
    power_to_db,
    mel_filterbank,
    spectrogram,
    istft,
    stft,
    BM25Retriever,
    TfidfVectorizer,
    PorterStemmer,
    GemmaForCausalLM,
    Gemma,
    MistralForCausalLM,
    Mistral,
    DebertaForSequenceClassification,
    DeBERTa,
    RobertaForMaskedLM,
    RobertaForSequenceClassification,
    RoBERTa,
    MoE,
    MixtureOfExperts,
    TopKRouter,
    Expert,
    SlidingWindowAttention,
    DeepSeekMLA,
    MultiHeadLatentAttention,
    AlexNet,
    AvgPool2D,
    BatchNorm2D,
    CBAM,
    AtrousConv2D,
    CIoULoss,
    DilatedConv2D,
    FeaturePyramidNetwork,
    PANet,
    DIoULoss,
    DiceLoss,
    FocalLoss,
    GIoULoss,
    TverskyLoss,
    ChannelShuffle,
    Conv2D,
    ConvNeXt,
    ConvNeXtTiny,
    ConvTranspose2D,
    Dense,
    DenseNet121,
    DenseNet169,
    DenseNet201,
    DepthwiseSeparableConv2D,
    EfficientNetB0,
    FCN,
    FCN8s,
    GlobalAvgPool2D,
    GoogLeNet,
    GradCAM,
    GroupedConv2D,
    InceptionV1,
    InceptionV3,
    LeNet5,
    Linear,
    MaxPool2D,
    MobileNetV1,
    MobileNetV2,
    MobileNetV3,
    NeuralNetwork,
    ResNet18,
    ResNet34,
    ResNet50,
    ResNet101,
    ResNet152,
    ResNeXt50,
    ResNeXt101,
    SEBlock,
    Sequential,
    ShuffleNetV1,
    ShuffleNetV2,
    SqueezeNet,
    SwinTransformer,
    SwinT,
    DeiT,
    DeiTTiny,
    DeepLabV3Plus,
    SegmentAnythingModel,
    UNet,
    VGG11,
    VGG13,
    VGG16,
    VGG19,
    VisionTransformer,
    ViT,
    ViTBase,
    ViTTiny,
    ZFNet,
    YOLOHead,
    SSDHead,
    RetinaNetHead,
    generate_anchor_grid,
    # NLP
    BERT,
    BPETokenizer,
    BaseTokenizer,
    BertForMaskedLM,
    BertForSequenceClassification,
    BiLSTM,
    CharacterTokenizer,
    GPT,
    GPTForCausalLM,
    GRU,
    GenerationConfig,
    GroupedQueryAttention,
    LLaMA,
    LSTM,
    LearnedPositionalEmbedding,
    LlamaForCausalLM,
    MiniGPT,
    MultiHeadAttention,
    RMSNorm,
    RNN,
    RoPE,
    SentencePieceTokenizer,
    Seq2SeqTransformer,
    SinusoidalPositionalEncoding,
    SwiGLU,
    T5,
    TextGenerator,
    TokenEmbedding,
    WhitespaceTokenizer,
    WordPieceTokenizer,
    WordTokenizer,
    RWKV6,
    RetNet,
    Mamba,
    DeepSeekV3,
    Qwen2_5,
    BitNet158,
    DPOTrainer,
    KTOTrainer,
    ORPOTrainer,
    SpeculativeDecoder,
    StructuredJSONDecoder,
    train,
)
from .evaluation import (
    EvaluationResult,
    evaluate,
    accuracy_score,
    log_loss,
    mean_squared_error,
    r2_score,
    roc_auc_score,
    pr_auc_score,
)
from .explainability import (
    ExplanationResult,
    explain,
    IntegratedGradients,
    SmoothGrad,
    DeepLIFT,
    AttentionRollout,
    DirectLogitAttribution,
    WachterCounterfactualExplainer,
    TCAV,
)

from .pipeline import PipelineResult, TransformationState, pipeline


class EDAWrapper:
    @staticmethod
    def image(
        dataset_path: str,
        save_reports: bool = False,
        save_dir: Optional[str] = None,
    ) -> Any:
        if save_reports and save_dir is None:
            save_dir = "chokkhu_outputs/image_reports"
        return ImageEDA(
            dataset_path=dataset_path, save_reports=save_reports, save_dir=save_dir
        )

    @staticmethod
    def tabular(
        dataset_path: str,
        save_reports: bool = False,
        save_dir: Optional[str] = None,
        target_col: Optional[str] = None,
    ) -> Any:
        if save_reports and save_dir is None:
            save_dir = "chokkhu_outputs/tabular_reports"
        return tabular_fn(
            dataset_path=dataset_path,
            target_col=target_col,
            save_reports=save_reports,
            save_dir=save_dir,
        )


eda = EDAWrapper()

from .models.gnn import (
    GCN,
    GAT,
    GraphSAGE,
    GIN,
    normalize_adjacency,
    LaplacianPositionalEncoding,
    Graphormer,
    RGCNClassifier,
    EGNN,
    TemporalGraphNetwork,
    HGNN,
)

from .models.rl import (
    DQN,
    DoubleDQN,
    DuelingDQN,
    ReplayBuffer,
    PrioritizedReplayBuffer,
    REINFORCE,
    ActorCritic,
    PPO,
    SAC,
    EpsilonGreedyBandit,
    UCB1Bandit,
    ThompsonSamplingBandit,
    LinUCBBandit,
    DecisionTransformer,
    HindsightExperienceReplay,
    GoalConditionedDQN,
)

from .models.timeseries import (
    ARIMA,
    ExponentialSmoothing,
    NBEATS,
    NHITS,
    PatchTST,
    decompose_series,
    ConformalPredictor,
    conformal_interval,
    MatrixProfile,
    find_motifs,
    find_discords,
    ExtendedKalmanFilter,
    UnscentedKalmanFilter,
    ParticleFilter,
    RaoBlackwellizedParticleFilter,
)

from .automl import (
    AutoTrainer,
    AutoMLResult,
    auto_train,
    BayesianOptimization,
    Hyperband,
    BOHB,
    SuperLearner,
    StackingEnsemble,
    GeneticPipelineSearch,
    DynamicEnsembleSelection,
)

from .models.retrieval import (
    HNSWIndex,
    IVFPQIndex,
    RandomHyperplaneLSH,
    MinHashLSH,
    DenseRetriever,
    reciprocal_rank_fusion,
    BM25Plus,
    OkapiBM25,
    HybridReranker,
)

from .models.recommendation import (
    SVDRecommender,
    SVDPlusPlus,
    ImplicitALS,
    NMFRecommender,
    BayesianPersonalizedRanking,
    NeuralCollaborativeFiltering,
    WideAndDeep,
    DeepFM,
    DLRM,
    SASRec,
    GRU4Rec,
    hit_rate_at_k,
    ndcg_at_k,
    mrr_at_k,
    precision_at_k,
    recall_at_k,
    map_at_k,
)

from .models.causal import (
    PropensityModel,
    PropensityScoreMatching,
    InverseProbabilityWeighting,
    DoublyRobustLearner,
    SLearner,
    TLearner,
    XLearner,
    NOTEARSCausalDiscovery,
    PCAlgorithm,
    TwoModelUplift,
    ClassTransformationUplift,
    qini_curve,
    qini_score,
    cumulative_gain_curve,
    uplift_at_k,
    TwoStageLeastSquares,
    InstrumentalGMM,
    DoubleMLPLR,
    RLearner,
)

from .models.survival import (
    KaplanMeierFitter,
    NelsonAalenFitter,
    logrank_test,
    CoxPHRegression,
    DeepSurv,
    concordance_index,
    brier_score_loss,
    integrated_brier_score,
)

from .models.multimodal import (
    CLIP,
    CLIPVisionEncoder,
    CLIPTextEncoder,
    SigLIP,
    LLaVALinearProjector,
    LLaVAMLPProjector,
    PerceiverResampler,
    CLAP,
    CLAPAudioEncoder,
    CLAPTextEncoder,
)

from .models.sciml import (
    PINN,
    DifferentiableParticleFluid,
    BurgersPINN,
    HeatPINN,
    WavePINN,
    HarmonicOscillatorPINN,
    SymbolicRegressor,
    NeuralODE,
    SpectralConv2d,
    FourierNeuralOperator2D,
    SparseGaussianProcessRegression,
    VariationalSparseGP,
)

from .fairness import (
    demographic_parity_difference,
    demographic_parity_ratio,
    equal_opportunity_difference,
    equalized_odds_difference,
    disparate_impact_ratio,
    theil_index,
    fairness_report,
    ReweighingTransformer,
    DisparateImpactRemover,
    ThresholdOptimizer,
)

from .compression import (
    UniformQuantizer,
    PostTrainingQuantizer,
    QuantizedLinear,
    MagnitudePruner,
    GlobalMagnitudePruner,
    KnowledgeDistiller,
    FeatureDistiller,
)

from .models.vision_3d import (
    TNet,
    PointNetClassifier,
    PointNetSegmenter,
    PointNet2Classifier,
    SetAbstractionModule,
    farthest_point_sampling,
    ball_query,
    PositionalEncoder,
    NeRFMLP,
    volume_render,
    generate_camera_rays,
    GaussianSplatting3D,
    quaternion_to_rotation_matrix,
)

from .models.nlp.agents import (
    Tool,
    ToolParameter,
    ToolRegistry,
    ReActAgent,
    AgentAction,
    AgentFinish,
    AgentStep,
    ChainOfThought,
    TreeOfThoughts,
    GraphOfThoughts,
    MultiAgentCoordinator,
    ReflexionEngine,
    SelfConsistency,
)


from .privacy import (
    LaplaceMechanism,
    GaussianMechanism,
    DP_SGD,
    FederatedClient,
    FederatedServer,
)
from .quantum import (
    QuantumCircuit,
    VariationalQuantumClassifier,
    QuantumKernel,
)
from .geospatial import (
    SpatialWeights,
    morans_i,
    local_morans_i,
    SpatialAutoregression,
    GeographicallyWeightedRegression,
    OrdinaryKriging,
)
from .tda import (
    VietorisRipsComplex,
    PersistenceDiagram,
    PersistenceLandscape,
    PersistenceImage,
    bottleneck_distance,
)


from .continual import (
    ElasticWeightConsolidation,
    EWC,
    DarkExperienceReplay,
    DERPlusPlus,
)
from .clustering import (
    SpectralGraphClusterer,
)
from .optimal_transport import (
    SinkhornOptimalTransport,
    sinkhorn_distance,
    WassersteinBarycenter,
    wasserstein_barycenter,
    SinkhornDivergence,
)
from .transformation import (
    SymbolicFeatureSynthesizer,
    SymbolicProgram,
)
from .models.nlp import (
    ByteTransformer,
    PagedKVCache,
    PagedAttention,
    ContinuousBatcher,
    Mamba2SSD,
    JambaHybridBlock,
)
from .models.gnn import (
    HeteroGCN,
    SpatioTemporalGCN,
    GraphCL,
    GRACE,
)


from .models.robotics import (
    DiffusionPolicy,
    RecurrentWorldModel,
    MPPITrajectoryOptimizer,
    RobotArmKinematics,
)
from .models.marl import (
    QMIX,
    VDN,
    NashEquilibriumSolver,
    ReplicatorDynamics,
    CombinatorialAuction,
)
from .models.bio import (
    GenomicTokenizer,
    GenomicBERT,
    ProteinContactMap,
)
from .models.anomaly import (
    SupportVectorDataDescription,
)
from .models.neurosymbolic import (
    DifferentiableLogicEngine,
    RotatE,
    TransE,
    DifferentiableILP,
    ProgramSynthesizer,
    DSLGrammar,
)
from .hdc import (
    HyperdimensionalVector,
    HDCClassifier,
)
from .safety import (
    StatisticalTextWatermark,
    RefusalDirectionProbe,
)
from .geometry import (
    PoincareBallEmbedding,
    LorentzManifold,
)
from .ranking import (
    NeuralSort,
    DifferentiableRankingLoss,
    LambdaMART,
    ListNet,
)
from .explainability import (
    ActivationPatchingEngine,
)


from .models.geometric import (
    SphericalHarmonics,
    SE3EquivariantConv,
)
from .optimization import (
    FollowTheRegularizedLeader,
    HedgeAlgorithm,
    OptNet,
    KFAC,
)
from .information import (
    KraskovMutualInformation,
    MultivariateKDE,
)
from .models.energy import (
    EnergyBasedModel,
    SlicedScoreMatching,
    ScoreMatchingEBM,
    AnnealedLangevinDynamics,
)
from .models.trees import (
    M5ModelTree,
    RuleFitRegressor,
    RuleFitClassifier,
)
from .uncertainty import (
    ConformalizedQuantileRegression,
    QuantileRegressor,
)


__all__ = [
    "Discriminator",
    "Generator",
    "WGANGP",
    "DCGAN",
    "DenoisingMLP",
    "SinusoidalTimeEmbedding",
    "DDPM",
    "VectorQuantizer",
    "VQVAE",
    "VAE",
    "VelocityMLP",
    "FlowMatching",
    "RectifiedFlow",
    "AffineCouplingLayer",
    "RealNVP",
    "LoRALinear",
    "LoRAAdapter",
    "LatentDiffusionModel",
    "LatentCrossAttentionBlock",
    "ControlNet",
    "ZeroConv2D",
    "ControlNetBlock",
    "CycleGAN",
    "CycleGANGenerator",
    "PatchGANDiscriminator",
    "Wav2Vec2",
    "Whisper",
    "WhisperEncoder",
    "WhisperDecoder",
    "ResidualVectorQuantizer",
    "VectorQuantizerStage",
    "VoiceActivityDetector",
    "AudioSpectrogramTransformer",
    "AST",
    "ConformerConvModule",
    "ConformerBlock",
    "Conformer",
    "BatchNorm1D",
    "DepthwiseConv1D",
    "Conv1D",
    "SpecAugment",
    "compute_deltas",
    "mfcc",
    "dct_type2",
    "melspectrogram",
    "power_to_db",
    "mel_filterbank",
    "spectrogram",
    "istft",
    "stft",
    "BM25Retriever",
    "TfidfVectorizer",
    "PorterStemmer",
    "GemmaForCausalLM",
    "Gemma",
    "MistralForCausalLM",
    "Mistral",
    "DebertaForSequenceClassification",
    "DeBERTa",
    "RobertaForMaskedLM",
    "RobertaForSequenceClassification",
    "RoBERTa",
    "MoE",
    "MixtureOfExperts",
    "TopKRouter",
    "Expert",
    "SlidingWindowAttention",
    "DeepSeekMLA",
    "MultiHeadLatentAttention",
    "eda",
    "load",
    "save",
    "clean",
    "LocalOutlierFactor",
    "EllipticEnvelope",
    "preprocess",
    "transform",
    "split",
    "PCA",
    "LDA",
    "LinearDiscriminantAnalysis",
    "TSNE",
    "UMAP",
    "SMOTE",
    "ImageAugmenter",
    "PolynomialFeatures",
    "train",
    "evaluate",
    "EvaluationResult",
    "explain",
    "IntegratedGradients",
    "SmoothGrad",
    "DeepLIFT",
    "AttentionRollout",
    "DirectLogitAttribution",
    "WachterCounterfactualExplainer",
    "TCAV",
    "ExplanationResult",
    "pipeline",
    "PipelineResult",
    "TransformationState",
    "NeuralNetwork",
    "Tensor",
    "Sequential",
    "Linear",
    "Dense",
    # Vision
    "Conv2D",
    "MaxPool2D",
    "AvgPool2D",
    "GlobalAvgPool2D",
    "DepthwiseSeparableConv2D",
    "GroupedConv2D",
    "ChannelShuffle",
    "ConvTranspose2D",
    "BatchNorm2D",
    "SEBlock",
    "CBAM",
    "AtrousConv2D",
    "CIoULoss",
    "DilatedConv2D",
    "FeaturePyramidNetwork",
    "PANet",
    "DIoULoss",
    "DiceLoss",
    "FocalLoss",
    "GIoULoss",
    "TverskyLoss",
    "LeNet5",
    "AlexNet",
    "ZFNet",
    "YOLOHead",
    "SSDHead",
    "RetinaNetHead",
    "generate_anchor_grid",
    "VGG11",
    "VGG13",
    "VGG16",
    "VGG19",
    "GoogLeNet",
    "InceptionV1",
    "InceptionV3",
    "ResNet18",
    "ResNet34",
    "ResNet50",
    "ResNet101",
    "ResNet152",
    "ResNeXt50",
    "ResNeXt101",
    "DenseNet121",
    "DenseNet169",
    "DenseNet201",
    "SqueezeNet",
    "SwinTransformer",
    "SwinT",
    "DeiT",
    "DeiTTiny",
    "MobileNetV1",
    "MobileNetV2",
    "MobileNetV3",
    "ShuffleNetV1",
    "ShuffleNetV2",
    "EfficientNetB0",
    "ConvNeXt",
    "ConvNeXtTiny",
    "UNet",
    "FCN",
    "FCN8s",
    "DeepLabV3Plus",
    "SegmentAnythingModel",
    "VisionTransformer",
    "ViT",
    "ViTTiny",
    "ViTBase",
    "GradCAM",
    # NLP
    "BaseTokenizer",
    "CharacterTokenizer",
    "WordTokenizer",
    "WhitespaceTokenizer",
    "BPETokenizer",
    "WordPieceTokenizer",
    "SentencePieceTokenizer",
    "TokenEmbedding",
    "SinusoidalPositionalEncoding",
    "LearnedPositionalEmbedding",
    "RoPE",
    "RNN",
    "LSTM",
    "BiLSTM",
    "GRU",
    "MultiHeadAttention",
    "GroupedQueryAttention",
    "RMSNorm",
    "SwiGLU",
    "BERT",
    "BertForSequenceClassification",
    "BertForMaskedLM",
    "GPT",
    "MiniGPT",
    "GPTForCausalLM",
    "LLaMA",
    "LlamaForCausalLM",
    "Seq2SeqTransformer",
    "T5",
    "GenerationConfig",
    "RWKV6",
    "RetNet",
    "Mamba",
    "DeepSeekV3",
    "Qwen2_5",
    "BitNet158",
    "DPOTrainer",
    "KTOTrainer",
    "ORPOTrainer",
    "SpeculativeDecoder",
    "StructuredJSONDecoder",
    # Preprocessing & Metrics
    "StandardScaler",
    "MinMaxScaler",
    "RobustScaler",
    "PowerScaler",
    "QuantileScaler",
    "RFESelector",
    "accuracy_score",
    "roc_auc_score",
    "pr_auc_score",
    "log_loss",
    "mean_squared_error",
    "r2_score",
    # GNN
    "GCN",
    "GAT",
    "GraphSAGE",
    "GIN",
    "normalize_adjacency",
    "LaplacianPositionalEncoding",
    "Graphormer",
    "RGCNClassifier",
    "EGNN",
    "TemporalGraphNetwork",
    "HGNN",
    # Reinforcement Learning
    "DQN",
    "DoubleDQN",
    "DuelingDQN",
    "ReplayBuffer",
    "PrioritizedReplayBuffer",
    "REINFORCE",
    "ActorCritic",
    "PPO",
    "SAC",
    "EpsilonGreedyBandit",
    "UCB1Bandit",
    "ThompsonSamplingBandit",
    "LinUCBBandit",
    "DecisionTransformer",
    # Time Series
    "ARIMA",
    "ExponentialSmoothing",
    "NBEATS",
    "NHITS",
    "PatchTST",
    "decompose_series",
    "ConformalPredictor",
    "conformal_interval",
    "MatrixProfile",
    "find_motifs",
    "find_discords",
    # AutoML
    "AutoTrainer",
    "AutoMLResult",
    "auto_train",
    "BayesianOptimization",
    "Hyperband",
    "BOHB",
    "SuperLearner",
    "StackingEnsemble",
    "GeneticPipelineSearch",
    "DynamicEnsembleSelection",
    # Vector Retrieval
    "HNSWIndex",
    "IVFPQIndex",
    "RandomHyperplaneLSH",
    "MinHashLSH",
    "DenseRetriever",
    "reciprocal_rank_fusion",
    "BM25Plus",
    "OkapiBM25",
    "HybridReranker",
    # Recommendation Systems
    "SVDRecommender",
    "SVDPlusPlus",
    "ImplicitALS",
    "NMFRecommender",
    "BayesianPersonalizedRanking",
    "NeuralCollaborativeFiltering",
    "WideAndDeep",
    "DeepFM",
    "DLRM",
    "SASRec",
    "GRU4Rec",
    "hit_rate_at_k",
    "ndcg_at_k",
    "mrr_at_k",
    "precision_at_k",
    "recall_at_k",
    "map_at_k",
    # Causal Inference & Uplift
    "PropensityModel",
    "PropensityScoreMatching",
    "InverseProbabilityWeighting",
    "DoublyRobustLearner",
    "SLearner",
    "TLearner",
    "XLearner",
    "TwoModelUplift",
    "ClassTransformationUplift",
    "qini_curve",
    "qini_score",
    "cumulative_gain_curve",
    "uplift_at_k",
    # Survival Analysis & Reliability
    "KaplanMeierFitter",
    "NelsonAalenFitter",
    "logrank_test",
    "CoxPHRegression",
    "DeepSurv",
    "concordance_index",
    "brier_score_loss",
    "integrated_brier_score",
    # Multi-Modal Vision-Language & Audio-Language
    "CLIP",
    "CLIPVisionEncoder",
    "CLIPTextEncoder",
    "SigLIP",
    "LLaVALinearProjector",
    "LLaVAMLPProjector",
    "PerceiverResampler",
    "CLAP",
    "CLAPAudioEncoder",
    "CLAPTextEncoder",
    # Scientific Machine Learning & PINNs
    "PINN",
    "BurgersPINN",
    "HeatPINN",
    "WavePINN",
    "HarmonicOscillatorPINN",
    "SymbolicRegressor",
    "NeuralODE",
    # Algorithmic Fairness & Bias Mitigation
    "demographic_parity_difference",
    "demographic_parity_ratio",
    "equal_opportunity_difference",
    "equalized_odds_difference",
    "disparate_impact_ratio",
    "theil_index",
    "fairness_report",
    "ReweighingTransformer",
    "DisparateImpactRemover",
    "ThresholdOptimizer",
    # Edge AI, Quantization & Compression
    "UniformQuantizer",
    "PostTrainingQuantizer",
    "QuantizedLinear",
    "MagnitudePruner",
    "GlobalMagnitudePruner",
    "KnowledgeDistiller",
    "FeatureDistiller",
    # 3D Computer Vision, Point Clouds & Neural Radiance (NeRF & 3DGS)
    "TNet",
    "PointNetClassifier",
    "PointNetSegmenter",
    "PointNet2Classifier",
    "SetAbstractionModule",
    "farthest_point_sampling",
    "ball_query",
    "PositionalEncoder",
    "NeRFMLP",
    "volume_render",
    "generate_camera_rays",
    "GaussianSplatting3D",
    "quaternion_to_rotation_matrix",
    # Autonomous AI Agents & Execution Engines
    "Tool",
    "ToolParameter",
    "ToolRegistry",
    "ReActAgent",
    "AgentAction",
    "AgentFinish",
    "AgentStep",
    "ChainOfThought",
    "TreeOfThoughts",
    "GraphOfThoughts",
    "MultiAgentCoordinator",
    "ReflexionEngine",
    "SelfConsistency",
    # Privacy-Preserving AI & Federated Learning
    "LaplaceMechanism",
    "GaussianMechanism",
    "DP_SGD",
    "FederatedClient",
    "FederatedServer",
    # Quantum Machine Learning (QML Simulator)
    "QuantumCircuit",
    "VariationalQuantumClassifier",
    "QuantumKernel",
    # Geo-Spatial Machine Learning & Spatial Statistics
    "SpatialWeights",
    "morans_i",
    "local_morans_i",
    "SpatialAutoregression",
    "GeographicallyWeightedRegression",
    "OrdinaryKriging",
    # Topological Data Analysis (TDA)
    "VietorisRipsComplex",
    "PersistenceDiagram",
    "PersistenceLandscape",
    "bottleneck_distance",
    "PagedKVCache",
    "PagedAttention",
    "ContinuousBatcher",
    "Mamba2SSD",
    "JambaHybridBlock",
    "ElasticWeightConsolidation",
    "EWC",
    "DarkExperienceReplay",
    "DERPlusPlus",
    "HeteroGCN",
    "SpatioTemporalGCN",
    "SinkhornOptimalTransport",
    "sinkhorn_distance",
    "WassersteinBarycenter",
    "wasserstein_barycenter",
    "SymbolicFeatureSynthesizer",
    "SymbolicProgram",
    "DiffusionPolicy",
    "RecurrentWorldModel",
    "MPPITrajectoryOptimizer",
    "QMIX",
    "VDN",
    "NashEquilibriumSolver",
    "GenomicTokenizer",
    "GenomicBERT",
    "ProteinContactMap",
    "DifferentiableLogicEngine",
    "RotatE",
    "TransE",
    "HyperdimensionalVector",
    "HDCClassifier",
    "DiscreteTextDiffusion",
    "RobotArmKinematics",
    "DifferentiableParticleFluid",
    "StatisticalTextWatermark",
    "RefusalDirectionProbe",
    "NOTEARSCausalDiscovery",
    "PCAlgorithm",
    "PoincareBallEmbedding",
    "LorentzManifold",
    "ReplicatorDynamics",
    "CombinatorialAuction",
    "ActivationPatchingEngine",
    "ClassifierFreeGuidance",
    "DiffusionInpainter",
    "ByteTransformer",
    "NeuralSort",
    "DifferentiableRankingLoss",
    "SphericalHarmonics",
    "SE3EquivariantConv",
    "FollowTheRegularizedLeader",
    "HedgeAlgorithm",
    "KraskovMutualInformation",
    "MultivariateKDE",
    "EnergyBasedModel",
    "SlicedScoreMatching",
    "M5ModelTree",
    "RuleFitRegressor",
    "RuleFitClassifier",
    "OptNet",
    "SinkhornDivergence",
    "SupportVectorDataDescription",
    "SpectralGraphClusterer",
    "DifferentiableILP",
    "DiffusionTransformer",
    "DiTBlock",
    "AdaLNZero",
    "KFAC",
    "ExtendedKalmanFilter",
    "UnscentedKalmanFilter",
    "HindsightExperienceReplay",
    "GoalConditionedDQN",
    "ConformalizedQuantileRegression",
    "QuantileRegressor",
    "SpectralConv2d",
    "FourierNeuralOperator2D",
    "TwoStageLeastSquares",
    "InstrumentalGMM",
    "LambdaMART",
    "ListNet",
    "ScoreMatchingEBM",
    "AnnealedLangevinDynamics",
    "PersistenceImage",
    "ParticleFilter",
    "RaoBlackwellizedParticleFilter",
    "DoubleMLPLR",
    "RLearner",
    "SparseGaussianProcessRegression",
    "VariationalSparseGP",
    "GraphCL",
    "GRACE",
    "ProgramSynthesizer",
    "DSLGrammar",
    "TIESMerging",
    "DARE",
    "SLERP",
    "RegMean",
    "FrankWolfeEnsemble",
    "SISARetraining",
    "FisherScrubbing",
    "SCRUB",
    "NullspaceConceptScrubbing",
    "TopKSAE",
    "JumpReLU",
    "ActivationPatching",
    "MCTSNode",
    "MonteCarloTreeSearchReasoning",
    "ProcessRewardModel",
    "STaR",
    "ReflexionLoop",
]
